Add cross-compiler check

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13,6 +13,7 @@ board="versatilepb"
 cross_prefix=arm-none-eabi-
 debug="yes"
 
+
 containsElement () {
   local e
   for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
@@ -38,6 +39,14 @@ if ! containsElement "$board" "${boards[@]}"
 then
   echo "Invalid board: $board"
   echo "Supported boards are: ${boards[*]}"
+  exit 1
+fi
+
+gcc="$cross_prefix"gcc
+if ! type "$gcc" >/dev/null 2>&1
+then
+  echo "Invalid cross-compilation prefix: $cross_prefix"
+  echo "Please check that $gcc is in your \$PATH and try again"
   exit 1
 fi
 
